#!/bin/bash

export DJANGO_SETTINGS_MODULE="whats_fresh.settings"
export WF_CONFIG_DIR=/home/tschuy/projects/whats-fresh-api/config
cd /home/tschuy/projects/whats-fresh-api

source ~/.virtualenvs/whats-fresh/bin/activate

function run() {
    echo "Running on http://127.0.0.1:8080"
    python /home/tschuy/projects/whats-fresh-api/manage.py runserver 0.0.0.0:8080
}
